### ISSUE TITLE
Can not pass the `decorator` add_view parameter to Service

### ISSUE THREAD

**Issue by dairiki** [mozilla-services/cornice#198]
Pyramid supports adding arbitrary decorators to view callables.  This is done by passing a `decorator` argument to `config.add_view`.  One can pass most `add_view` options to the `Service` contructor and they will be passed on to `config.add_view` where appropriate.  However, due to a name conflict with the (unrelated) `Service.decorator` method, it is not currently possible to pass a `decorator` argument to `Service`.

(The `decorator` argument can be successfully used on individual calls to `Service.add_view`.)

The problem arises from around [line 184 of service.py](https://github.com/mozilla-services/cornice/blob/master/cornice/service.py#L184), where `Service.__init__` copies all its arguments to attributes.  Adding a conditional to skip setting the `decorator` attribute fixes the problem.

If this is acceptable, I can submit a pull request.

**Comment by tisdall** [comment]
This seems to be fixed.

**Comment by dairiki** [comment]
Thanks @tisdall. Yes, it was fixed long ago. Closing.
