### ISSUE TITLE
How to change the returned HTTP status code after colander validation error

### ISSUE THREAD

**Issue by andrewjburnett** [mozilla-services/cornice#283]
If I am using cornice with added schema validation by Colander, is it possible to change the returned http status code when there is an error? For example, if my colander schema is invalid, Cornice seems to take the liberty of returning a '400 Bad Request' status code on my behalf. How would I go about returning a different status code, say '422 Unprocessable Entity', for this type of error?

**Comment by ametaireau** [comment]
It's possible to [change the reponse code used in validation](https://github.com/mozilla-services/cornice/blob/master/cornice/errors.py#L15), yes.

However, I don't think there is an easy option to set this up with cornice when the validation is done by the Colander schema directly.

The creation of the `Error` object is done [on each new request](https://github.com/mozilla-services/cornice/blob/11d7a3b28f0463871670dd3a96cecf18b00611f3/cornice/pyramidhook.py#L141-L142). One simple way to do what you want would be this (in your app initialisation):

```python
from pyramid.events import NewRequest
from cornice.errors import Errors

def attach_custom_request(event):
    setattr(request, 'errors', Errors(request, status=422))

config.add_subscriber(attach_custom_request, NewRequest)
```

**Comment by andrewjburnett** [comment]
Thanks @ametaireau! I didn't think they're was; I had looked through the source. I just wanted to be sure something wasn't going over my head. I appreciate the help.
