### ISSUE TITLE
1.0.0 Broke resource routing

### ISSUE THREAD

**Issue by aguereca** [mozilla-services/cornice#290]
Asume a file `my_views.py`

``` python
from cornice.resource import resource, view

@resource(collection_path='/user/{id}/follow', path='/user/{id}/follow')
class UserFollowViews(object):
    ...
    @view(validators=(validate_authentication, validate_user))
    def post(self):
    ....


@resource(collection_path='/user/{id}/following', path='/user/{id}/following')
class UserFollowingViews(object):
    ...
    @view(validators=(validate_authentication, validate_user))
    def collection_get(self):
    ....
```

With 1.0.0 , using proutes I can see broken routes and all requests accessing them will return 404 Not Found:

Name                    |      Pattern                  |    Method   |   View       
------------------------|-----------------------------|---------------|---------
userfollowviews |  /user/{id}/follow | POST   |  my_views.UserFollowViews.post__POST
userfollowingviews | /user/{id}/following  |   *  |  `<unknown>`

I had to downgrade and fix versions to 0.20.0 to solve this.

After a quick look into the commits of 1.0.0 and can't single on a commit that might cause this, a more experienced eye on the routing internals could be of help here.

**Comment by dairiki** [comment]
There is not enough detail (or I'm not smart enough) to completely understand your example, but why do you have `collection_path` and `path` set to the same thing?  That makes no sense to me — though, again, perhaps I am being dense.  (Should a POST to <samp>/user/<i>{id}</i>/follow</samp> be routed to `UserFollowViews.post` or `UserFollowViews.collection_post`?)

Note that if you don't need any of the the `collection_` views, you needn't set a `collection_path`.

**Comment by ametaireau** [comment]
This is probably related to this: https://github.com/mozilla-services/cornice/pull/287 and I believe @circlingthesun should have thoughts about that.

That being said, I wouldn't recommend using resources if you don't need them. Also, reproducing this with a test case would be very helpful in order to fix it.

**Comment by circlingthesun** [comment]
This is probably related to: https://github.com/mozilla-services/cornice/blob/ee7f8750f3d0f281d9e4cf005fd43e50818bbf18/cornice/resource.py#L29.

The order in which the standard service and the collection service is created was swapped around. This should not make a difference, unless, as @dairiki ```collection_path``` and ```path``` is set to the same thing. In this case, the ```collection_path``` will overwrite the route defined by ```path``.

An exception should probably be raised when  ```collection_path == path```.

**Comment by aguereca** [comment]
Thanks for all your feedback, each have bring a piece of truth to this, so I've make a few new tests and effectively the problem is that I had defined the same route for path and collection_path, my oversight mainly because both are required and before 1.0.0 if the class defining the resource didn't have a method for that path then was simply ignored.
For completeness, previous pseudo example is fixed by this update:

``` python
from cornice.resource import resource, view

@resource(collection_path='/user/{user_id}/follow', path='/user/{user_id}/follow/{id}')
class UserFollowViews(object):
    ...
    @view(validators=(validate_authentication, validate_user))
    def post(self):
    ....


@resource(collection_path='/user/{user_id}/following', path='/user/{user_id}/following/{id}')
class UserFollowingViews(object):
    ...
    @view(validators=(validate_authentication, validate_user))
    def collection_get(self):
    ....
```

The warning implemented by @circlingthesun will be very helpful for anybody else upgrading to 1.0.0 on same situation. I'll actually recommend adding it into the list of breaking changes of 1.0.0, because upgrading effectively breaks routing on incorrectly defined resources.

**Comment by ametaireau** [comment]
I can't add it to 1.0.0 but I will in 1.0.1 for sure!
