### ISSUE TITLE
Defining a 'collection_path' along with 'path' in Service

### ISSUE THREAD

**Issue by bomb-on** [mozilla-services/cornice#299]
I have a simple Service configuration, similar to this:
```
desc = """\
Here be description.
"""

service = Service(name='contacts', path='/contacts/{id}', description=desc)


@service.get()
def get_contacts(request):
    """Here be docs."""
    return {'result': 'OK'}
```
When I try
```$ curl -i http://127.0.0.1:6543/contacts/1```
I get a proper response:
```
HTTP/1.1 200 OK
Content-Length: 16
Content-Type: application/json; charset=UTF-8
Date: Tue, 19 May 2015 15:36:27 GMT
Server: waitress

{"result": "OK"}
```
however, if I try
```$ curl -i http://127.0.0.1:6543/contacts/```
I get
```
HTTP/1.1 404 Not Found
Content-Length: 806
Content-Type: text/html; charset=UTF-8
Date: Tue, 19 May 2015 15:36:39 GMT
Server: waitress
```
Isn't it possible to define endpoints for Service like this? Something similar to Resource's `path` and `collection_path`?

**Comment by bomb-on** [comment]
Hmm... Anyone? Any tip?

**Comment by ametaireau** [comment]
A service only has one path. If you want to have something like Resource's path and collection_path, you'll need to register two services.

Eg. in you case, if you want to have two endpoints `/contacts/{id}` and `/contacts`, you'll need to register two services with the different paths.

**Comment by bomb-on** [comment]
Thanks for clarifying!

**Comment by tisdall** [comment]
I found that I can declare a path such as `/contacts*id` and then it will match both `/contacts/` and `/contacts/1`.  You then get a tuple back in `requests.matchdict['id']`.  This is the "remainder match" talked about here:  http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/urldispatch.html#route-pattern-syntax  So, it may have the unintended side effect of also matching '/contacts/1/this/that/oops'.

**Comment by tisdall** [comment]
> Eg. in you case, if you want to have two endpoints /contacts/{id} and /contacts, you'll need to register two services with the different paths.

This won't match `/contacts/`.  You'd have to have a third endpoint to match the one with the trailing slash.
