### ISSUE TITLE
all travis tests are run on python2.7

### ISSUE THREAD

**Issue by tisdall** [mozilla-services/cornice#311]
I'm guessing it has to do with this:  https://github.com/mozilla-services/cornice/blob/master/.travis.yml#L2

If you go to https://travis-ci.org/mozilla-services/cornice you can see that all 4 tests are run with Python 2.7 .

**Comment by tisdall** [comment]
wait...  looking at it a little more, it seems like each one is using python 2.7 to run tox which then runs the appropriate version of python.

Maybe someone should double check that I'm reading that before I close this.  :)

**Comment by dairiki** [comment]
@tisdall Your second analysis is correct. Py27 is used to run tox, but the grid settings for `$TOX_ENV` cause tox to run the tests under various versions of python (or to run flake8.)  If you have any doubt about this you can look at the test output (on travis) for each of the test runs, where it is clear which version of python is running the tests.

**Comment by tisdall** [comment]
@dairiki - no, I was pretty sure because I also looked at the output of the test run, but I didn't want to jump to another conclusion like I did when I opened this issue.  ;)
