### ISSUE TITLE
Support for per http request acls?

### ISSUE THREAD

**Issue by mamalos** [mozilla-services/cornice#322]
At the moment, acl statements are supported only in Service constructors and in resource decorators. What if somebody wanted to provide different acls in each http, REST request? OK, the resource decorator allows for a collection_acl statement, which gives one more degree of freedom wrt to acls, but still, per http request acls are not supported.

Is there a plan towards this direction? If not, where should I focus my attention in case I could help?

**Comment by ametaireau** [comment]
With pyramid, the way to handle permissions and ACLs is [with a context factory and authorization policies](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/urldispatch.html#using-security-with-urldispatch).

So, I'm not sure to understand what the "per http request acls" thing means. Do you have an example ?

**Comment by mamalos** [comment]
OK, you're right, I'll give you an example.

Without cornice, in pyramid's configuration I'm able to provide different factories for different routes using the add_route statement along with its factory parameter, eg:

config.add_route('/something/', factory=view_all)
config.add_route('/something/view/{id:[0-9]+}', factory=view_single)

where view_all and view_single are context factories containing (or returning) acls.

This way, by adding a different factory for each route (I'm talking about URL Dispatch), I have the freedom to use whatever factory I wish for every url, and hence every different "action". There's no analogous syntax in view_config decorators, because context is route related. This is why config.add_route is used in my example. 

Now, in the case of cornice, I am unable to achieve this behaviour. Moreover, I assume that it'd be analogously "inappropriate" adding such support in the view decorator, and hence my question.

In case this doesn't make any sense, then I might have gotten it all wrong! :):) (though it works in my code :))

**Comment by mamalos** [comment]
Ah, and by no means do I imply that there's no work around on this by creating an appropriate context that works for all the specific Service http requests, but still, to my understanding, the default pyramid functionality cannot be used within cornice.

**Comment by tisdall** [comment]
@mamalos - cornice is kind of like wrapper with added tools that goes over pyramid.  You still have all the same functionality of pyramid.  The `Service` methods essentially make the `add_route` and `view_config` calls for you.  If you look at http://cornice.readthedocs.org/en/latest/api.html you can see that you can pass a `factory` to the `Service` on init.  I haven't used that myself (yet) but that seems to be what you're looking for.

**Comment by mamalos** [comment]
@tisdall, I am not sure I understood your answer correctly. What I'm saying is that the Service method is only accepting one acl (or factory) argument, which is the same for all routes (and the resource decorator accepts one more, namely the collection_acl). In pyramid, on the other hand, you can associate a different factory to each route separately.

**Comment by tisdall** [comment]
@mamalos - I haven't used the Resource decorator, but it seems that the functionality can be duplicated with two Service calls.  I think in order to do something like what you're showing with calls to `add_route`, you'd need to have two separate Service calls any way.

**Comment by ametaireau** [comment]
Yes, this is something we don't support in cornice, simply because we never had this use case.

We always register [one route per service](https://github.com/mozilla-services/cornice/blob/master/cornice/pyramidhook.py#L186) and then [one view per method](https://github.com/mozilla-services/cornice/blob/master/cornice/pyramidhook.py#L221-L237) (more or less).

I'm not sure if we should do things differently, to be honest, but I would gladly review any approach that would not make the thing overly complex.

**Comment by tisdall** [comment]
There's no reason you can't apply two Service decorators to the same method.

**Comment by ametaireau** [comment]
OH yes, you can apply two Service decorators to the same function if you want.

**Comment by dairiki** [comment]
Another (IMHO more pyramidic) way to deal with this is to use a single *acl* for the service and different *permissions* for different methods.

E.g. (mostly ripped from the [pyramid docs](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#assigning-acls-to-your-resource-objects), and completely untested): 
```
from cornice import Service
from pyramid.security import Allow, Everyone, DENY_ALL

class RootFactory(object):
    def __init__(self, request):
        pass

    __acl__ = [
        (Allow, Everyone, 'view'),
        (Allow, 'group:editors', 'edit'),
        DENY_ALL,
        ] 

user_info = Service(name='users', path='/{username}/info', factory=RootFactory)

@user_info.get(permission='view')
def get_info(request):
    ....

@user_info.post(permission='edit')
def set_info(request):
    ....

**Comment by mamalos** [comment]
@dairiki, I know that this is how cornice uses ACL's and that's the exact reason why I've published this issue. In contrast to your comment, Pyramid does not work the same way. Pyramid allows for per route factories while cornice doesn't (or at least to my understanding).

@ametaireau and @tisdall,  do you mean that applying multiple service decorators to the same function is supported at the moment or that it is relatively easy to add as a feature?

**Comment by mamalos** [comment]
Ah, and thanks all for your interest and answers!

**Comment by tisdall** [comment]
@mamalos, I'm confused about the issue you're having.  Cornice is just passing those arguments on to Pyramid, there's no difference because all the ACL stuff is handled by Pyramid.  Each `Service` is a route and can have it's own ACL factory.

And, yes, you can already stack decorators on a single function just like you can already do with Pyramid's `view_config`.

**Comment by dairiki** [comment]
So, another angle of attack would be
```
def acl_factory(request):
    return METHOD_SPECIFIC_ACLS.get(request.method, DEFAULT_ACL)

user_info = Service(name='users', path='/{username}/info', acl=acl_factory)

... 
```

As already noted, cornice generates one route per service.  That is, I'm pretty sure, the "right" thing to do, at least in the normal case.  The pyramid RouteMapper performs a linear search through the route list for each request, so one does not want to create unnecessary routes.

Do you have a use case to share (to motivate the need for per-view ACLs)?

**Comment by mamalos** [comment]
@tisdall, after reading your last comment, I finally understood your suggestions and have understood where my problem is; and sorry everybody for the confusion caused, I'm still new to pyramid and cornice and hence still a bit dizzy while learning it :). So, here goes my problem once more, and I think you'll understand it this time:

In an imaginary CRUD application, without cornice (just pyramid), people would usually add four routes, one for the each CRUD operation. So in plain pyramid, *usually*, each CRUD operation can have its own acl (through context or factory), since acls are passed through routes.

In cornice, on the other hand, when using the resource decorator (which is where I'm facing my problem, and is my design preference over Service), there are two routes (one used for collection_ and one for each item separately) and various HTTP methods, (GET, POST, PUT, DELETE, etc.). But in cornice, in order to address each CRUD operation, we're using a different HTTP method, and not (necessarily) a different route. Hence, operational wise (and this seems to be a design side-effect now that I think I'm starting to understand it:) ), since CRUD operations in cornice are taking advantage of HTTP methods as well, and the same route can be used for a different CRUD operation based on the HTTP method used, it's consequential that each CRUD operation is not able to have its own acl.

And now I -finally- understand that this is pyramid's "limitation" and not cornice's.

**Comment by mamalos** [comment]
And @dairiki, I think your solution would work great!

**Comment by dairiki** [comment]
Just a note, for completeness (and argumentativeness): the one-route-per-service limitation is a cornice design decision (IMO, the correct one.)  Pyramid does allow multiple routes for the same path (or "pattern"), differentiated by other predicates
```
config.add_route('user_post', '/users/{userid}', request_method='POST', factory=factory_for_post)
config.add_route('user', '/users/{userid}', factory=default_factory)

config.add_view(user_get, request_method='GET', route_name='user')
config.add_view(user_post, route_name='user_post')
```
IMHO(fwiw), it is best to avoid multiple routes with the same pattern, when possible.

**Comment by mamalos** [comment]
Hmmm...@dairiki, now you are giving me ideas, and I have to reclaim this issue! :):)

From what you're saying (and from your code), it seems that pyramid is able to achieve per route-and-method acls while cornice can't. Would it be possible for cornice to support this as well?

**Comment by dairiki** [comment]
Since the views associated with a single service conceptually (are supposed to) represent different actions against a single entity, I, personally, still think the best (and most "pyramidic") approach to permissions is to have a single ACL associated with the the entity ("resource"), which each of the actions ("methods") on that entity requiring a (possibly) different permission (as is done in my first example, [above](https://github.com/mozilla-services/cornice/issues/322#issuecomment-119696710).) The single ACL describes who is allowed to do what to the entity in question, whereas the permission associated with each view describes what is being done.

If what you really want is per-method ACLs, this can be expressed with a single ACL, too.  (For an illustration, In my first example, above, just change the names of the `view` and `edit` permissions to "GET" and "POST", respectively.)


Again, do you have a use case to motivate the case for per-view (or per-method) ACLs?

**Comment by mamalos** [comment]
@dairiki, one example I can think of is the following: I am using per object permissions via ACLs. This means that the final ACL is computed -asking the database- each time the user makes a request. From a utilisation perspective, most performed requests are collection_get (imagine a forum, for example, where users are most commonly watching threads containing lists of posts), where there's no need of computing per item ACLs. So, for such requests, I could have simply added a simple (Allow, Everyone, 'view') ACE that makes no database queries using the collection_acl that I mentioned earlier. But this collection_acl is affecting collection_post as well, which does need to check the database (to check whether the user belongs to a group that allows them to post a new item). 

So, design wise, from a performance perspective, I am not quite happy with not being able to address this issue. On the other hand, the solution you posted earlier (https://github.com/mozilla-services/cornice/issues/322#issuecomment-120001224) does seem to fulfill my needs, but still there may be a different example that will not be able to be addressed that easily with cornice, even though pyramid would allow for an easier approach. 

So, what I imply is that just because I have not thought of an example that could be dealt with multiple routes per request in cornice, doesn't mean that nobody can. I assume that pyramid's architects allowed for multiple routes per request for some reason as well.

Thanks again for all the help.

**Comment by tisdall** [comment]
@mamalos, I think I see you're issue now...  In your example, you want your ACL on the "views" to not bother querying for the user's group but when they write you do want it.  If both the "view" and the "write" share the same ACL factory then the DB query happens both times.  This the issue?

**Comment by mamalos** [comment]
Yep, exactly!

But this can be resolved with the code in @dairiki 's previous comment (https://github.com/mozilla-services/cornice/issues/322#issuecomment-120001224). On the other hand, there may be issues that will not be able to be resolved as easily.

**Comment by dairiki** [comment]
Another hack (or "performance tweak") which should work for your case without breaking the one-acl-per-resource paradigm, is to make the `__acl__` a generator so that if an earlier ACE "hits", the remainder of the ACL need not be computed.:
```
from cornice import Service
from pyramid.decorator import reify
from pyramid.security import Allow, Everyone, DENY_ALL

class UserResource(object):
    def __init__(self, request):
        self.request = request

    @property  # (the property decorator is unnecessary for pyramid >= 1.5)
    def __acl__(self):
        yield Allow, Everyone, 'view'
        for acl in self._acl_heavy:
            yield acl

    @reify
    def _acl_heavy(self):
        # compute and return the db-intenstive tail part of the acl
        slow_acl = [
            (Allow, 'group:editors', 'edit'),
            DENY_ALL,
            ]
        return slow_acl

user_info = Service(name='users', path='/{username}/info', factory=UserResource)

@user_info.get(permission='view')
def get_info(request):
    ....

@user_info.post(permission='edit')
def set_info(request):
    ....
```

**Comment by tisdall** [comment]
@dairiki nice!  I think that's a better solution then testing the http method.

**Comment by mamalos** [comment]
Thanks @dairiki, this looks nice! I'll try it.
