### ISSUE TITLE
trivial performance slowdown

### ISSUE THREAD

**Issue by JamesHutchison** [mozilla-services/cornice#325]
in pyramidhook.py:

```python
            if 'content_type' in args:
                supported_contenttypes.extend(
                    service.get_contenttypes(method,
                                             filter_callables=True))
                supported_contenttypes.extend(
                    request.info.get('supported_contenttypes', []))
                supported_contenttypes = list(set(supported_contenttypes))
```

It appears that `supported_contenttype` is created as a list, converted to a set, then converted back to a list?

**Comment by tisdall** [comment]
I'm guessing they're trying to eliminate duplicates in the list.

**Comment by JamesHutchison** [comment]
Ah I see. I think this should be done after the error is detected though, prior to the error message generation. There's no performance benefit (only a cost) to reducing the list down prior to checking to see if one item exists in the list.

**Comment by tisdall** [comment]
The list isn't stored, so probably the elimination of duplicates could just be done in the error message generation.

**Comment by ametaireau** [comment]
We cannot know for what the list would be used. Currently in cornice it's only used for error generation.

Maybe we should just use sets everywhere and convert all the lists to sets when we add them to the mix.

**Comment by leplatrem** [comment]
I'm closing this. Those operations are performed a very small lists and does not affect performance.
Please re-open with some benchmark/figures to prove me wrong ;)
