### ISSUE TITLE
Allow a global CORS policy configuration

### ISSUE THREAD

**Issue by vcatalano** [mozilla-services/cornice#331]
It would be nice if there was a way to configure a global CORS policy for all resources. Although the documentation shows how an external object can be used to set the `cors_policy` for each resource (http://cornice.readthedocs.org/en/latest/api.html), it still doesn't seem very DRY. I currently have a large number of resources defined throughout my code and I will have to modify each one in order to support CORS. By providing a single point of configuration for all resources - or even a global default configuration - I think this would make dealing with CORS much nicer.

Something like this could be used in `main()`:

```python
config.route_prefix = '/api'
config.cors_policy = {'origins': ('*',), 'max_age': 42, 'credentials': True}

# Alternatively
config.cors_default_policy = {'origins': ('*',), 'max_age': 42, 'credentials': True}
```

**Comment by ametaireau** [comment]
One way to do it is to define a Service class which inherits the cornice Service class and use it everywhere else :)

**Comment by vcatalano** [comment]
That is what I ended up doing. I still think a global default policy would be helpful. I may end up branching to add this implementation unless someone has some objections to handing CORS policies in this manner?

**Comment by ametaireau** [comment]
Why not! Fill a PR away :-)
