### ISSUE TITLE
HTTP method override

### ISSUE THREAD

**Issue by zupo** [mozilla-services/cornice#333]
Some of our API consumers use old/limited libraries that can only send GET and POST requests. I found that Flask supports this on the middleware level (http://flask.pocoo.org/docs/0.10/patterns/methodoverrides/) and am wondering what is the best approach for Cornice? Shall we add documentation on how to do it with some middleware code/configuration or shall we built support for overriding HTTP method into Cornice itself?

**Comment by tisdall** [comment]
It looks like that example is standard WSGI middleware.  So, you can just as easily use it with pyramid which is what cornice is built on.  After a very quick search, here's an example of using a middleware with pyramid: http://stackoverflow.com/questions/4936507/how-do-i-write-a-logging-middleware-for-pyramid-pylons-2

As the page you point to says: "In that case it’s possible to 'proxy' HTTP methods through another HTTP method in total violation of the protocol."  It's a total hack and should probably only be used as long as you're stuck using that old/limited library.  The benefit of the hack is that when you don't need it any more, you can simply remove it and everything will work properly.  So, I don't think it should be included in Cornice, but I think it'd be great to be included in the docs (basically, that's exactly what Flask seems to have done).

**Comment by zupo** [comment]
Great!
