### ISSUE TITLE
add_view; includeme not working as expected

### ISSUE THREAD

**Issue by delijati** [mozilla-services/cornice#334]
Following a minimal example of a app structured with `includeme` and `add_view`. I marked the parts with `FIXME` that are not working like expected (thats how pyramid also allows them).

*demoapp/__init__.py*:
````python
from pyramid.config import Configurator

def main(global_config, **settings):
    config = Configurator(settings=settings)
    config.include("cornice")
    config.include("demoapp.views.includeme")
    # FIXME shouldn't be necessary -> config.scan("demoapp.views")
    return config.make_wsgi_app()
````

*demoapp/views.py*:
```python
from collections import defaultdict
from pyramid.view import view_config
from cornice import Service

_USERS = defaultdict(dict)

# FIXME this should also work in includeme
user_info = Service(name='users', path='/{username}/info')

def get_info(request):
    username = request.matchdict['username']
    return _USERS[username]

def set_info(request):
    username = request.matchdict['username']
    _USERS[username] = request.json_body
    return {'success': True}

def who(request):
    return {"usernames": _USERS.keys()}

def includeme(config):
    # FIXME user_info should be defined here
    user_info.add_view('post', set_info)
    user_info.add_view('get', get_info)

    config.add_route("who", "/who")
    config.add_view(who, route_name="who", renderer="json")
````

The easiest solution would be, to add `config` as a paramater to Service!?

**Comment by ametaireau** [comment]
`Service` doesn't currently have any notion of pyramid `config`. We do all the registration in pyramid in `pyramidhook` instead.

In the second case, I don't get why `user_info` (that you defined) isn't present where you put the FIXME.

Also, I don't quite get what you're trying to do here, as it seems you don't want to use the `Service` `add_view` directly. Cornice provides you decorators to ease this process, actually :-)

**Comment by delijati** [comment]
If i put `user_info` in `def includeme`, the views are not registered. 

I like the pyramid *imperative* style of defining views and grouping all needed information in one place `def includeme` (separating views and configuration).

Mixing *declarative*  and *imperative* with `@view_config` and `add_route` and in worst case seperating them in two files, makes it for me to cluttered.

Anyway i got it working by calling `add_cornice_service` see `XXX`:

```python
from collections import defaultdict
from cornice import Service

_USERS = defaultdict(dict)

def get_info(request):
    username = request.matchdict['username']
    return _USERS[username]

def set_info(request):
    username = request.matchdict['username']
    _USERS[username] = request.json_body
    return {'success': True}

def who(request):
    return {"usernames": _USERS.keys()}

def includeme(config):
    user_info = Service(name='users', path='/{username}/info')
    user_info.add_view('post', set_info)
    user_info.add_view('get', get_info)
    # XXX calling add_cornice_service to register views
    config.add_cornice_service(user_info)

    config.add_route("who", "/who")
    config.add_view(who, route_name="who", renderer="json")
```

But now the sphinx documentation is not being extracted. After modifying the sphinx extension, calling `includeme` i also got the sphinx docu working:

```python
class ServiceDirective(Directive):
....
    def run(self):
    ...
        import cornice
        from pyramid.config import Configurator
        config = Configurator()
        cornice.includeme(config)

        # import the modules, which will populate the SERVICES variable.
        for module in self.options.get('modules'):
            if module in MODULES:
                reload(MODULES[module])
            else:
                mod = import_module(module)
                if hasattr(mod, 'includeme'):
                    mod.includeme(config)
                MODULES[module] = mod
```

As i showed it is possible to register views with `add_view` in a `includeme`. As it seems it is only now the sphinx extension, documentation which should be edited maybe with an extra option `app_includeme`:

```
.. cornice-autodoc::
   :modules: your.module
   :services: name1, name2
   :service: name1 # no need to specify both services and service.
   :ignore: a comma separated list of services names to ignore
   :app_includeme: your.app
```

**Comment by ametaireau** [comment]
Yes! Don't hesitate to open a pull request for it.

**Comment by brianthelion** [comment]
@ametaireau This seems related to the points raised in [your 2012 blog post](http://blog.notmyidea.org/refactoring-cornice.html). What's the status of branch [refactor-the-world](https://github.com/mozilla-services/cornice/tree/refactor-the-world) at this point? I don't see any pull requests against it. Thanks!

**Comment by ametaireau** [comment]
I think everything in there was merged to master.

**Comment by brianthelion** [comment]
Good to know, thanks!

**Comment by delijati** [comment]
Can be closed since its merged.
