### ISSUE TITLE
content_type not handled properly if it is a function

### ISSUE THREAD

**Issue by bomb-on** [mozilla-services/cornice#343]
I have defined `view` decorator in my `resource`:

    @view(renderer='json', content_type='application/json')

and when I call it without `Content-Type` properly defined, I get a 415 error.

However, if I want to call a function instead of defining a string for `content_type`

    @view(renderer='json', content_type=content_type)

and in some other file i have defined that function:

    def content_type(request):
        # interact with request
        return 'application/json'

it won't produce error 415, but it will return a 200 response.

Why is this happening? For some reason I'm sure it was working few months ago when I defined it in this way...

**Comment by leplatrem** [comment]
> Why is this happening? For some reason I'm sure it was working few months ago when I defined it in this way...

I may be wrong, but I see nothing in the code base that would support providing content_type as a callable. That could be a relevant contribution IMO if you need it!

**Comment by bomb-on** [comment]
Hm, to be honest, I didn't go trough the code base, but I thought that [this](https://cornice.readthedocs.org/en/latest/validation.html#content-type-validation) part of documentation is saying it is possible. Or is it only a `service`'s feature?

**Comment by leplatrem** [comment]
OH! You are right, the documentation explicitly says it should work! That's a bug then! (either in code or documentation)

**Comment by Natim** [comment]
This is needed by: https://github.com/Kinto/kinto/pull/461 and https://github.com/mozilla-services/cliquet/pull/667

**Comment by amotl** [comment]
This should have worked, right. Have been there the other day (see #91) so will have a look if nobody is already into it.

**Comment by amotl** [comment]
Hey there, i had a look and found the following things:
- The documentation [1] is correct by stating 

  > The callable should return a **list** of accepted content types

  Here, @bomb-on tried to return a **single** internet media type **as scalar**, hence the misbehavior of Cornice
- However, when specifying the list of accepted content types as plain value, Cornice allows lists **and** scalars

To improve the functionality:
- Make content_type checks using callables capable of returning single internet media types as scalars, see #350

[1] https://cornice.readthedocs.org/en/latest/validation.html#content-type-validation

Maybe consider relabeling this from "bug" to "enhancement".

**Comment by bomb-on** [comment]
Thanks for looking into this! I see you discussed it and changed the code base a bit, but just to check, does this mean that `content_type` can now accept functions?

**Comment by amotl** [comment]
@bomb-on: ``content_type`` always accepted functions, but the machinery was improved now to be able to cope with return values made of scalar strings. Before, it only accepted lists of media type strings but was poor on reporting that properly, so your use case failed somehow silently:

    def content_type(request):
        # interact with request
        return 'application/json'

This should work now as we're using ``to_list(...)`` to always convert the callback return value to a list before propagating it internally.

**Comment by bomb-on** [comment]
@amotl ah, I understand now... Ok, thank you one more time guys for all the effort and keep up with good work ;)

**Comment by almet** [comment]
thanks for the kind words :)
